allowBuilds:
  '@clerk/shared': false
  '@google/genai': true
  '@sentry/cli': true
  esbuild: false
  protobufjs: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
storeDir: /Users/ricglz/play-repos/flashcard-app/.pnpm-store
