allowBuilds:
  '@clerk/shared': false
  '@google/genai': true
  '@sentry/cli': true
  esbuild: false
  protobufjs: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
patchedDependencies:
  multi-llm-ts@5.1.0-beta4: patches/multi-llm-ts@5.1.0-beta4.patch
storeDir: /Users/ricglz/play-repos/flashcard-app/.pnpm-store
